def detect_eavesdropping(sender_key, receiver_key):
    """
    Detect potential eavesdropping during quantum key exchange between sender and receiver.
    
    Parameters:
    sender_key (str): Quantum key generated by the sender.
    receiver_key (str): Quantum key generated by the receiver.
    
    Returns:
    eavesdropping_detected (bool): True if eavesdropping is detected, False otherwise.
    """
    # Eavesdropping detection algorithm for quantum key exchange
    eavesdropping_detected = detect(sender_key, receiver_key)
    return eavesdropping_detected
